### ISSUE TITLE
Optionally filter out previous backports in the merge list

### ISSUE THREAD

**Issue by degville** [canonical-docs/canonical-doc-utils#5]
This:

0 - #1923 - 2.2.0 as latest stable in Getting started                                                              
1 - #1922 - updated download links for 2.2.0 release                                                               
2 - #1919 - Publish 2.2 docs                                                                                       
3 - #1917 - Add upgrade caveat to troubleshooting                                                                  
4 - #1915 - Add not regarding add-model space delay                                                                

Instead of:

│0 - #1925 - bp1922 to 2.2 (manual)                                                                                 
1 - #1924 - Backport #1923 to 2.2                                                                                  
2 - #1923 - 2.2.0 as latest stable in Getting started                                                              
3 - #1922 - updated download links for 2.2.0 release                                                               
4 - #1919 - Publish 2.2 docs                                                                                       
5 - #1918 - bp-to-2.2: #1917 from degville/troubleshoot-upgrades                                                   
6 - #1917 - Add upgrade caveat to troubleshooting                                                                  
7 - #1916 - Backport #1915 to 2.2                                                                                  
8 - #1915 - Add not regarding add-model space delay                                                                
9 - #1913 - Backport #1911 to 2.1                                                                                  
10 - #1912 - Backport #1911 to 2.2

**Comment by evilnick** [comment]
yes, it does get cluttered. want to keep it fast though :)

I will take a look for 0.2.17

**Comment by degville** [comment]
:+1: This affects me too.
